set(DEPENDENT_MP_BIN2HEXusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP "c:/Program Files/Microchip/xc32/v5.10/bin/xc32-bin2hex.exe")
set(DEPENDENT_DEPENDENT_TARGET_ELFusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP ${CMAKE_CURRENT_LIST_DIR}/../../../../out/usart_ring_buffer_interrupt_wbz451_curiosity/wbz451_curiosity.elf)
set(DEPENDENT_TARGET_DIRusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP ${CMAKE_CURRENT_LIST_DIR}/../../../../out/usart_ring_buffer_interrupt_wbz451_curiosity)
set(DEPENDENT_BYPRODUCTSusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP ${DEPENDENT_TARGET_DIRusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP}/${sourceFileNameusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP}.c)
add_custom_command(
    OUTPUT ${DEPENDENT_TARGET_DIRusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP}/${sourceFileNameusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP}.c
    COMMAND ${DEPENDENT_MP_BIN2HEXusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP} --image ${DEPENDENT_DEPENDENT_TARGET_ELFusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP} --image-generated-c ${sourceFileNameusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP}.c --image-generated-h ${sourceFileNameusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP}.h --image-copy-mode ${modeusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP} --image-offset ${addressusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP} 
    WORKING_DIRECTORY ${DEPENDENT_TARGET_DIRusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP}
    DEPENDS ${DEPENDENT_DEPENDENT_TARGET_ELFusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP})
add_custom_target(
    dependent_produced_source_artifactusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP 
    DEPENDS ${DEPENDENT_TARGET_DIRusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP}/${sourceFileNameusart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_9E_ixBiP}.c
    )
