include("${CMAKE_CURRENT_LIST_DIR}/rule.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/file.cmake")

set(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_library_list )

# Handle files with suffix s, for group wbz451_curiosity-XC32
if(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_FILE_TYPE_assemble)
add_library(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_assemble OBJECT ${usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_FILE_TYPE_assemble})
    usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_assemble_rule(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_assemble)
    list(APPEND usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_library_list "$<TARGET_OBJECTS:usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_assemble>")

endif()

# Handle files with suffix S, for group wbz451_curiosity-XC32
if(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_FILE_TYPE_assembleWithPreprocess)
add_library(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_assembleWithPreprocess OBJECT ${usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_FILE_TYPE_assembleWithPreprocess})
    usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_assembleWithPreprocess_rule(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_assembleWithPreprocess)
    list(APPEND usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_library_list "$<TARGET_OBJECTS:usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_assembleWithPreprocess>")

endif()

# Handle files with suffix [cC], for group wbz451_curiosity-XC32
if(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_FILE_TYPE_compile)
add_library(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_compile OBJECT ${usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_FILE_TYPE_compile})
    usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_compile_rule(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_compile)
    list(APPEND usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_library_list "$<TARGET_OBJECTS:usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_compile>")

endif()

# Handle files with suffix cpp, for group wbz451_curiosity-XC32
if(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_FILE_TYPE_compile_cpp)
add_library(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_compile_cpp OBJECT ${usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_FILE_TYPE_compile_cpp})
    usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_compile_cpp_rule(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_compile_cpp)
    list(APPEND usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_library_list "$<TARGET_OBJECTS:usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_compile_cpp>")

endif()

# Handle files with suffix [cC], for group wbz451_curiosity-XC32
if(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_FILE_TYPE_dependentObject)
add_library(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_dependentObject OBJECT ${usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_FILE_TYPE_dependentObject})
    usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_dependentObject_rule(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_dependentObject)
    list(APPEND usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_library_list "$<TARGET_OBJECTS:usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_dependentObject>")

endif()


# Main target for this project
add_executable(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_image_9E_ixBiP ${usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_library_list})

set_target_properties(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_image_9E_ixBiP PROPERTIES
    OUTPUT_NAME "wbz451_curiosity"
    SUFFIX ".elf"
    RUNTIME_OUTPUT_DIRECTORY "${usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_output_dir}")
target_link_libraries(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_image_9E_ixBiP PRIVATE ${usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_wbz451_curiosity_XC32_FILE_TYPE_link})

# Add the link options from the rule file.
usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_link_rule( usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_image_9E_ixBiP)

# Add bin2hex target for converting built file to a .hex file.
string(REGEX REPLACE [.]elf$ .hex usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_image_name_hex ${usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_image_name})
add_custom_target(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_Bin2Hex ALL
    COMMAND ${MP_BIN2HEX} \"${usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_output_dir}/${usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_image_name}\"
    BYPRODUCTS ${usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_output_dir}/${usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_image_name_hex}
    COMMENT "Convert built file to .hex")
add_dependencies(usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_Bin2Hex usart_ring_buffer_interrupt_wbz451_curiosity_wbz451_curiosity_image_9E_ixBiP)



